INSERT INTO puesto (id,nombre) VALUES (90,'Administrador de bases de datos');
INSERT INTO puesto (id,nombre) VALUES (91,'Administrador de comunicaciones');
INSERT INTO puesto (id,nombre) VALUES (92,'Administrador de plataformas');
INSERT INTO puesto (id,nombre) VALUES (93,'Administrador Sap Basis');
INSERT INTO puesto (id,nombre) VALUES (94,'Administrador Seguridad informatica');
INSERT INTO puesto (id,nombre) VALUES (95,'Analista Administrativo');
INSERT INTO puesto (id,nombre) VALUES (96,'Analista Contable');
INSERT INTO puesto (id,nombre) VALUES (97,'Analista Funcional');
INSERT INTO puesto (id,nombre) VALUES (98,'Analista RRHH');
INSERT INTO puesto (id,nombre) VALUES (99,'Cadete');
INSERT INTO puesto (id,nombre) VALUES (100,'Consultor');
INSERT INTO puesto (id,nombre) VALUES (101,'Desarrollador');
INSERT INTO puesto (id,nombre) VALUES (102,'Director');
INSERT INTO puesto (id,nombre) VALUES (103,'Ejecutivo comercial');
INSERT INTO puesto (id,nombre) VALUES (104,'Gerente');
INSERT INTO puesto (id,nombre) VALUES (105,'Instructor');
INSERT INTO puesto (id,nombre) VALUES (106,'Jefe de Area');
INSERT INTO puesto (id,nombre) VALUES (107,'Jefe de servicio');
INSERT INTO puesto (id,nombre) VALUES (108,'Lider de proyecto');
INSERT INTO puesto (id,nombre) VALUES (109,'Operador de contact center');
INSERT INTO puesto (id,nombre) VALUES (110,'Operador de Mesa de Ayuda');
INSERT INTO puesto (id,nombre) VALUES (111,'Operador Noc');
INSERT INTO puesto (id,nombre) VALUES (112,'Recepcionista');
INSERT INTO puesto (id,nombre) VALUES (113,'Maestranza');
INSERT INTO puesto (id,nombre) VALUES (114,'Supervisor');
INSERT INTO puesto (id,nombre) VALUES (115,'Tecnico de comunicaciones');
INSERT INTO puesto (id,nombre) VALUES (116,'Tecnico de hardware');
INSERT INTO puesto (id,nombre) VALUES (117,'Tecnico de Soporte');
INSERT INTO puesto (id,nombre) VALUES (118,'Tecnico instalador');
INSERT INTO puesto (id,nombre) VALUES (119,'Tester');
